import type { HdxWhitelistEntry, PahWhitelistEntry, PolkadotWhitelistEntry } from '@polkadot-api/descriptors';

type WhiteListEntry = HdxWhitelistEntry | PahWhitelistEntry | PolkadotWhitelistEntry;

export const whitelist: WhiteListEntry[] = [
  'tx.Assets.transfer',
  'tx.Assets.transfer_keep_alive',
  'tx.Balances.transfer_keep_alive',
  'tx.Tokens.transfer',
  'tx.Tokens.transfer_keep_alive',
  'tx.ForeignAssets.transfer',
  'tx.Utility.batch_all',
  'tx.PolkadotXcm.limited_teleport_assets',
  'tx.XcmPallet.limited_teleport_assets',
  'tx.PolkadotXcm.reserve_transfer_assets',
  'tx.XcmPallet.reserve_transfer_assets',
  'tx.PolkadotXcm.limited_reserve_transfer_assets',
  'tx.XcmPallet.limited_reserve_transfer_assets',
  'tx.PolkadotXcm.teleport_assets',
  'tx.XcmPallet.teleport_assets',
  'tx.PolkadotXcm.transfer_assets',
  'tx.XcmPallet.transfer_assets',
  'tx.XTokens.transfer',
  'tx.XTokens.transfer_multiasset',
  'query.System.Account',
  // 'query.System.Number',
  'query.AssetConversion.Pools',
  'query.PoolAssets.Asset',
  'query.PoolAssets.Account',
  'query.Assets.Asset',
  'query.Assets.Account',
  'query.Assets.Metadata',
  'query.ForeignAssets.Asset',
  'query.ForeignAssets.Account',
  'query.ForeignAssets.Metadata',
  'query.Balances.TotalIssuance',
  'query.Balances.Account',
  'query.Tokens.Accounts',
  'const.AssetConversion.LPFee',
  'const.Balances.ExistentialDeposit',
  'api.AssetConversionApi.*',
];
